name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
          SHOW_PROJECTS: true
          SHOW_OS: true
          SHOW_TIMEZONE: false
          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_SHORT_INFO: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LINES_OF_CODE: false
          SHOW_LOC_CHART: false
          SHOW_UPDATED_DATE: false
          SHOW_LANGUAGE_PER_REPO: false
          SYMBOL_VERSION: 1
          LOCALE: en
          COMMIT_MESSAGE: "docs: update wakatime stats"
          COMMIT_USERNAME: "anuragxo"
          COMMIT_EMAIL: "anuragxo.dev@gmail.com"
